### ISSUE TITLE
GoogleMediaFrameworkDemo project not working, file, method declaration missing.

### ISSUE THREAD

**Issue by szhussain** [googleads/google-media-framework-ios#88] opened 2016-12-08 11:31 UTC
I downloaded the GoogleMediaFrameworkDemo project but it is giving errors.

This is how My PodFile look like:
platform :ios, ‘6.1’
target ‘GoogleMediaFrameworkDemo’ do
pod 'GoogleMediaFramework', '~> 1.0'
end

In 'VideoListController.h' it is giving error 'Unknown type name GMFIMASDKAdService, did you mean GMFAdService' on this line;
@property(nonatomic, strong) GMFIMASDKAdService *adService;

In 'VideoListController.m' it is giving error 'No visible @interface for GMFPlayerViewController declares the selector 'loadStreamWithURL:imaTag:'' on this line;
[self.videoPlayerViewController loadStreamWithURL:[NSURL URLWithString:video.videoURL] imaTag:video.adTagURL];

What should i do to resolve these errors and run the project.

**Comment by shawnbuso** [comment] 2016-12-12 16:13
Hey there,

Sorry for the confusion - we're having issues pushing the latest GMF version to CocoaPods because of how we link the IMA SDK, and that mehod is only defined as of the latest version. I'm working on getting this fixed and will keep you updated.

Thanks,
Shawn

**Comment by szhussain** [comment] 2016-12-13 08:09
Hope you will fix it soon.

A few questions i wanted to ask, does GMF support 'adaptive bit rate' (low/high streaming based on network speed) and 'digital video recording' (to view content which was aired earlier that day) ???

Thanks.

**Comment by shawnbuso** [comment] 2016-12-13 14:46
We use AVPlayer under the hood, so we support any video format that AVPlayer supports. For adaptive bitrate, AVPlayer supports HLS streams (m3u8). For DVR, do you mean watching a live stream and rewinding it, or just watching a standard video file that was recorded earlier in the day? The latter is definitely supported. For the former, it looks like it depends on how your server is sending the stream (see [this StackOverflow question](http://stackoverflow.com/questions/26532209/does-avplayer-support-live-event-rewind)).

**Comment by shawnbuso** [comment] 2017-02-09 17:22
Going to close as a duplicate of #89

**Closed by shawnbuso** 2017-02-09 17:22 UTC
